function datum(
  value: number | null,
  source = value == null ? "unknown" : "observed",
) {
  return { value, source };
}

export function graphFixture() {
  return {
    schema_version: 1,
    generated_at: 1_800_000_000_000,
    process_started_at: 1_799_999_000_000,
    stale_after_sec: 30,
    scope: { device_id: "camera-1", room_name: "Living room" },
    graph: {
      id: "flow",
      label: "Perception Flow",
      direction: "LR",
      layout: { rank_separation: 48, node_separation: 24 },
      groups: [
        { id: "source", label: "Source", order: 10 },
        { id: "output", label: "Output", order: 20 },
      ],
      nodes: [
        {
          id: "dynamic-a",
          kind: "source",
          label: "Decoded Stream",
          group: "source",
          rank: 0,
          order: 10,
          status: "ok",
          freshness: "fresh",
          last_observed_status: null as string | null,
          standalone: false,
          metrics: [
            {
              key: "queue_depth",
              label: "Queue depth",
              value: 2,
              unit: "frames",
              source: "observed",
              role: "state",
              severity: null,
              future_field: "ignored",
            },
          ],
          input: null,
          output: {
            width: datum(1920),
            height: datum(1080),
            fps: datum(15),
            frame_count: datum(60),
            duration_ms: datum(4000),
          },
          warnings: [],
          evidence: {
            trace_id: "trace-1",
            device_trace_id: "device-trace-1",
            observed_at: 1_800_000_000_000,
            age_ms: 250,
          },
        },
        {
          id: "dynamic-b",
          kind: "sink",
          label: "Result",
          group: "output",
          rank: 1,
          order: 10,
          status: "inactive",
          freshness: "fresh",
          last_observed_status: null as string | null,
          standalone: false,
          metrics: [],
          input: null,
          output: null,
          warnings: [],
          evidence: null,
        },
        {
          id: "audio-only",
          kind: "encoder",
          label: "Audio Encoder",
          group: "output",
          rank: 1,
          order: 20,
          status: "ok",
          freshness: "fresh",
          last_observed_status: null as string | null,
          standalone: true,
          metrics: [
            {
              key: "container",
              label: "Container",
              value: "m4a",
              unit: null,
              source: "observed",
              role: "output",
              severity: null,
            },
            {
              key: "has_audio",
              label: "Has audio",
              value: true,
              unit: null,
              source: "observed",
              role: "state",
              severity: null,
            },
          ],
          input: null,
          output: null,
          warnings: [],
          evidence: null,
        },
      ],
      edges: [
        {
          id: "dynamic-edge",
          from: "dynamic-a",
          to: "dynamic-b",
          label: "frames",
          active: false,
          status: "inactive",
          freshness: "fresh",
          last_observed_status: null as string | null,
          media: {
            width: datum(1920),
            height: datum(1080),
            fps: datum(15),
            frame_count: datum(60),
            duration_ms: datum(4000),
          },
          metrics: [],
          warnings: [],
          evidence: null,
        },
      ],
    },
    summary: {
      latest_trace_id: "trace-1",
      latest_device_trace_id: "device-trace-1",
      observed_at: 1_800_000_000_000,
      freshness: "fresh",
      devices: [
        {
          device_id: "camera-1",
          room_name: "Living room",
          trace_id: "trace-1",
          device_trace_id: "device-trace-1",
          observed_at: 1_800_000_000_000,
          freshness: "fresh",
          status: "ok",
        },
      ],
    },
  };
}
